name: Hello World
description: "Greet someone and record the time"
inputs:
  who-to-greet:
    required: true
    default: "World"
    description: "Who to greet"

outputs:
  time:
    description: "The time we greet you"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}
